using System;
using System.Collections.Generic;
using System.Text;


namespace CMP304_Assesment_Project
{
    /// <summary>
    /// store the data generated by all the classes so that they can be displayed to the user
    /// </summary>
    public class DataGathered
    {
        public string testResults { get; set; }
        public List<string> nonCompatibleFiles{ get; set; }

        //image path and prediction
        public List<string> processedImagesPath { get; set; }
        public List<string> processedImagesEmotion { get; set; }

        public List<float[]> processedImagesScore { get; set; }

    }
}
